apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-rvnmkbvp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-rvnmkbvp:fb9edce1945acdab041f8eb2f440bb8372cba988@sha256:5e8e5e3222471d6f0fd1638a7d029901df612729d1c3338e6c1d59e99d016663
          name: container-image
